"""kullanıcı tablosu

Revision ID: 99181ae5d64d
Revises: 
Create Date: 2022-12-08 13:49:16.114371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99181ae5d64d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullaniciadi', sa.String(length=64), nullable=True),
    sa.Column('eposta', sa.String(length=120), nullable=True),
    sa.Column('sifre_hash', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kullanici_eposta'), ['eposta'], unique=True)
        batch_op.create_index(batch_op.f('ix_kullanici_kullaniciadi'), ['kullaniciadi'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kullanici_kullaniciadi'))
        batch_op.drop_index(batch_op.f('ix_kullanici_eposta'))

    op.drop_table('kullanici')
    # ### end Alembic commands ###
